# Generated by Django 4.1.1 on 2022-11-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceimage',
            name='order_number',
            field=models.CharField(default='Order Number', max_length=50),
        ),
    ]
