# Generated by Django 4.1.1 on 2022-11-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sourceimage_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameNumberOrderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=30)),
                ('number', models.CharField(default='Number', max_length=30)),
                ('order_number', models.CharField(default='Order Number', max_length=50)),
            ],
        ),
    ]
